### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by nkr413** [FrozenAssassine/FluentEdit#2]
hello. please make a release version for download from github)

**Comment by nkr413** [comment]
can you also do .exe option for download ? I really want to try this editor, but for some reason msixbundle doesn't work.

**Comment by FrozenAssassine** [comment]
Unfortunately .exe is not supported by UWP apps. Why can't you install the msixbundle?

**Comment by nkr413** [comment]
okay. thank you. i will wait new release)

**Comment by FrozenAssassine** [comment]
@nkr413 I have published a msixbundle in the latest release, please check out if it works for you https://github.com/FrozenAssassine/FluentEdit/releases/tag/v1.1.0
